# frozen_string_literal: true

TECH_LEVELS = [
  {
    code: 0,
    descriptor: 'Primitive',
    short_description: 'Stone Age. No formal tools beyond the most primitive.',
    energy: 'Muscle',
    electronics: 'Mind',
    manufacturing: 'Hand tools',
    medical: 'Herbs',
    environmental: 'Early settlement',
    land: 'Cart',
    sea: 'Canoe, Raft',
    air: nil,
    space: nil,
    personal_military: 'Club, Spear, Bow',
    heavy_military: nil
  },
  {
    code: 1,
    descriptor: 'Primitive',
    short_description: 'Bronze and iron age. Primitive metalworking and weapons.',
    energy: 'Waterwheel',
    electronics: 'Abacus, heliograph',
    manufacturing: 'Milling machines',
    medical: 'Diagnosis',
    environmental: 'Bridges, cities',
    land: 'Wagon',
    sea: 'Galley',
    air: nil,
    space: nil,
    personal_military: 'Blades, Crossbow',
    heavy_military: 'Catapult'
  },
  {
    code: 2,
    descriptor: 'Primitive',
    short_description: 'Renaissance. Scientific method, early chemistry and astronomy.',
    energy: 'Windmill',
    electronics: 'Clockwork, printing',
    manufacturing: 'Cottage industry',
    medical: 'Anatomy',
    environmental: 'Land reclamation',
    land: 'Stagecoach',
    sea: 'Sailing Ship',
    air: nil,
    space: nil,
    personal_military: 'Early Firearm',
    heavy_military: 'Early Cannon'
  },
  {
    code: 3,
    descriptor: 'Primitive',
    short_description: 'Steam age. Industrial revolution beginning, primitive firearms.',
    energy: 'Steam, early battery',
    electronics: 'Telegraph',
    manufacturing: 'Factories',
    medical: 'Early surgery',
    environmental: 'Gas lighting',
    land: 'Early Train, Bicycle',
    sea: 'Early Steamship',
    air: 'Balloon',
    space: nil,
    personal_military: 'Foil, Musket',
    heavy_military: 'Cannon'
  },
  {
    code: 4,
    descriptor: 'Industrial',
    short_description: 'Early industrial. Plastics, radio, internal combustion.',
    energy: 'Electricity',
    electronics: 'Telephones',
    manufacturing: 'Assembly lines',
    medical: 'Anaesthetics',
    environmental: 'Hydroelectric dams',
    land: 'Train',
    sea: 'Steamship',
    air: 'Early Airplane, Dirigible',
    space: nil,
    personal_military: 'Revolver, Shotgun',
    heavy_military: 'Artillery'
  },
  {
    code: 5,
    descriptor: 'Industrial',
    short_description: 'Electrification. Telecommunications, early atomics and computing.',
    energy: 'Internal combustion',
    electronics: 'Radio, vacuum tubes',
    manufacturing: 'Heavy industry',
    medical: 'X-ray diagnosis',
    environmental: 'Skyscrapers',
    land: 'Automobile',
    sea: 'Submersible',
    air: 'Airplane',
    space: nil,
    personal_military: 'Rifle, Machinegun',
    heavy_military: 'Heavy Artillery, Tank'
  },
  {
    code: 6,
    descriptor: 'Industrial',
    short_description: 'Fission age. Nuclear power and advanced computing. Dawn of spaceflight.',
    energy: 'Fission',
    electronics: 'Television, transistors',
    manufacturing: 'Basic automation',
    medical: 'Tissue bioreactor',
    environmental: 'Air-conditioning',
    land: 'Amphibius Vehicle',
    sea: 'Hydrofoil, Nuclear Ship',
    air: 'Helicopter, Supersonic Jet',
    space: 'Rocket',
    personal_military: 'Auto Rifle, Rocket Launcher',
    heavy_military: 'Missile, Nuclear Weapons'
  },
  {
    code: 7,
    descriptor: 'Pre-Stellar',
    short_description: 'Early space age. Reliable orbital access, satellites, integrated circuits.',
    energy: 'Basic solar',
    electronics: 'Microchips, networks',
    manufacturing: 'Cad machines',
    medical: 'Organ transplants',
    environmental: 'High yield crops',
    land: 'High Speed Train',
    sea: 'Hovercraft',
    air: 'Vtol',
    space: 'Spaceplane',
    personal_military: 'Assault Rifle',
    heavy_military: 'Autocannon'
  },
  {
    code: 8,
    descriptor: 'Pre-Stellar',
    short_description: 'Interplanetary. Other worlds reachable; fusion power commercially viable.',
    energy: 'Basic fusion, Basic power cell',
    electronics: 'Mobile computer, Basic robot brains',
    manufacturing: 'Basic fabs, Orbital factories',
    medical: 'Basic clones, Early cybernetics, gene editing',
    environmental: 'Arcologies, Orbital spin cities',
    land: 'Autonomous Car, Walker',
    sea: 'Autonomous Ship',
    air: 'Autonomous Plane, Hypersonic Jet, Air/Raft',
    space: 'Early Grav',
    personal_military: 'Stun Weapons',
    heavy_military: 'Precision Weapons'
  },
  {
    code: 9,
    descriptor: 'Pre-Stellar',
    short_description: 'Jump age. Gravity control and jump drive. Interstellar colonisation possible.',
    energy: 'Improved solar',
    electronics: 'Core computers, Holographic projectors',
    manufacturing: 'External fabs',
    medical: 'Spare part clones',
    environmental: 'Underwater cities, early weather control',
    land: 'Superconducting Monorail Train',
    sea: nil,
    air: 'Grav Car',
    space: 'M-Drive, Jump-1',
    personal_military: 'Laser Rifle',
    heavy_military: 'Laser Gun, Grav Tank, Rail Gun'
  },
  {
    code: 10,
    descriptor: 'Early Stellar',
    short_description: 'Interstellar. Jump drives common; interstellar trade and colonisation boom.',
    energy: 'Basic fusion+, improved power cell',
    electronics: 'Advanced robot brains',
    manufacturing: 'Improved fabs, Robotic factories',
    medical: 'Hibernation, accelerated clones',
    environmental: 'Grav cities',
    land: 'Merges With Air',
    sea: 'Merges With Air',
    air: 'Universal Grav Vehicles',
    space: 'Beanstalk',
    personal_military: 'Advanced Rifle',
    heavy_military: 'Plasma Gun, Crystaliron'
  },
  {
    code: 11,
    descriptor: 'Early Stellar',
    short_description: 'AI age. First true artificial intelligence; Jump-2 drives.',
    energy: 'Advanced solar',
    electronics: nil,
    manufacturing: nil,
    medical: 'Brain transplants',
    environmental: 'Weather control',
    land: nil,
    sea: nil,
    air: nil,
    space: 'Jump-2',
    personal_military: 'Combat Armour',
    heavy_military: nil
  },
  {
    code: 12,
    descriptor: 'Average Stellar',
    short_description: 'Climate control. Planetary weather control; Jump-3 drives.',
    energy: 'Improved fusion, advanced power cell',
    electronics: 'Very advanced robot brains, basic meson comms',
    manufacturing: nil,
    medical: 'Full body cyborgs',
    environmental: 'Early terraforming',
    land: nil,
    sea: nil,
    air: 'Grav Belt',
    space: 'Jump-3',
    personal_military: 'Gauss Rifle, Plasma Gun',
    heavy_military: 'Gauss Cannon'
  },
  {
    code: 13,
    descriptor: 'Average Stellar',
    short_description: 'Battle dress. Cloned body parts; Jump-4 drives.',
    energy: 'Improved fusion plus',
    electronics: 'Neural link integration',
    manufacturing: 'Enhanced fabs, Basic nanobots',
    medical: 'Quick clones',
    environmental: 'Nanobot constructors',
    land: nil,
    sea: nil,
    air: nil,
    space: 'Jump-4',
    personal_military: 'Battledress',
    heavy_military: 'Fusion Gun'
  },
  {
    code: 14,
    descriptor: 'Average Stellar',
    short_description: 'Flying cities. Portable fusion weapons; Jump-5 drives.',
    energy: 'Collectors',
    electronics: 'Advanced meson comms',
    manufacturing: nil,
    medical: 'Reanimation',
    environmental: 'Mobile grav cities',
    land: nil,
    sea: nil,
    air: nil,
    space: 'Jump-5',
    personal_military: 'Fusion Gun',
    heavy_military: 'Bonded Superdense'
  },
  {
    code: 15,
    descriptor: 'High Stellar',
    short_description: 'Black globes. Synthetic anagathics extend human lifespan indefinitely.',
    energy: 'Advanced fusion',
    electronics: 'Self-aware brains',
    manufacturing: 'Improved nanobots',
    medical: 'Anagathics',
    environmental: 'Improved terraforming',
    land: nil,
    sea: nil,
    air: nil,
    space: 'Jump-6',
    personal_military: nil,
    heavy_military: 'Meson Gun, Black Globe'
  },
  {
    code: 16,
    descriptor: 'High Stellar',
    short_description: 'Transcendent. Technologies beyond the standard stellar classification.',
    energy: nil,
    electronics: 'Conscious Computers',
    manufacturing: nil,
    medical: nil,
    environmental: 'Global Terraforming',
    land: nil,
    sea: nil,
    air: nil,
    space: nil,
    personal_military: 'Plasma Rifle',
    heavy_military: 'Molecular Bonded'
  }
]
