pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  schema_search_path: 'public,shared_extensions'

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *pg_default
    database: mtu_development
  cache:
    <<: *sqlite
    database: storage/cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: storage/queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: storage/cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *pg_default
    database: mtu_test
  cache:
    <<: *sqlite
    database: storage/test_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: storage/test_cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *sqlite
    database: storage/cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: storage/queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: storage/cable.sqlite3
    migrations_paths: db/cable_migrate
